name: CI

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - scala: 2.12.21
            java: 11
          - scala: 3.8.4
            java: 17

    steps:
      - uses: actions/checkout@v7

      - uses: coursier/cache-action@v8
        continue-on-error: true

      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}

      - uses: sbt/setup-sbt@v1

      - name: build ${{ matrix.scala }}
        run: sbt ++${{ matrix.scala }} build

      - name: test coverage
        if: success() && matrix.scala == '2.12.21'
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: sbt ++${{ matrix.scala }} coverageReport coverageAggregate coveralls

      - name: slack
        uses: homoluctus/slatify@master
        if: failure() && github.ref == 'refs/heads/master'
        with:
          type: ${{ job.status }}
          job_name: Build
          url: ${{ secrets.SLACK_WEBHOOK }}
